name: Bug Report
description: Something isn't working
labels: ["type:bug", "needs:triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe what went wrong
      placeholder: When I tried to... it showed...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: How bad is it?
      options:
        - Blocker - Can't use the product
        - Major - Significant problem
        - Minor - Small issue
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Screenshots, logs, or steps to reproduce
    validations:
      required: false
