name: Bug Report
description: Report a bug
labels: ["type:bug"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project is affected?
      options:
        - Deployments (Smart Contracts)
        - Backend (Web3 API)
        - Game (Unity)
        - Frontend (Web)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Severity
      description: How bad is it?
      options:
        - High - Blocking / Critical
        - Medium - Important but workaround exists
        - Low - Minor issue
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: false
