name: Bug Report
description: Something isn't working
labels: ["type:bug", "needs:triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe what went wrong
      placeholder: When I tried to... it showed...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
    validations:
      required: false

  - type: checkboxes
    id: area
    attributes:
      label: Area (optional - developers will assign if unsure)
      description: Which parts seem affected?
      options:
        - label: Deployments (Smart Contracts)
        - label: Backend (Web3 API)
        - label: Game (Unity)
        - label: Frontend (Web)

  - type: dropdown
    id: severity
    attributes:
      label: How bad is it?
      options:
        - Blocker - Can't use the product
        - Major - Significant problem
        - Minor - Small issue or cosmetic
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce (if known)
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Screenshots or logs
      description: Anything that helps understand the issue
    validations:
      required: false
