name: Feature Request
description: Propose a new feature
labels: ["type:feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project does this affect?
      options:
        - Deployments (Smart Contracts)
        - Backend (Web3 API)
        - Game (Unity)
        - Frontend (Web)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this?
      options:
        - High - Do first
        - Medium - Do soon
        - Low - Do eventually
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want to build?
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know it's done?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
    validations:
      required: false
