name: Feature Request
description: Propose a new feature or improvement
labels: ["type:feature", "needs:triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What do you want?
      description: Describe the feature from a user perspective
      placeholder: As a player, I want to... so that...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High - Need this soon
        - Medium - Important but not urgent
        - Low - Nice to have
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any mockups, examples, or references?
    validations:
      required: false
