name: Tech Debt / Improvement
description: Code quality, refactoring, or developer experience
labels: ["type:tech-debt", "needs:triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What needs improvement?
      description: What technical issue should we address?
    validations:
      required: true

  - type: checkboxes
    id: area
    attributes:
      label: Area
      description: Which parts of the codebase?
      options:
        - label: Deployments (Smart Contracts)
        - label: Backend (Web3 API)
        - label: Game (Unity)
        - label: Frontend (Web)

  - type: textarea
    id: why
    attributes:
      label: Why is this important?
      description: What problems does this cause? What would improve?
    validations:
      required: false

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution (optional)
      description: Any ideas on how to fix it?
    validations:
      required: false
