name: Tech Debt / Improvement
description: Code quality, refactoring, or developer experience
labels: ["type:tech-debt", "needs:triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What needs improvement?
      description: What technical issue should we address?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this important?
      description: What problems does this cause?
    validations:
      required: false
